[project]
name = "python-metrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.7",
    "prometheus-client>=0.21.1",
    "uvicorn>=0.34.0",
]
