services:
  metrics-app:
    image: sesgoe/gmp-min-repro-metrics-quarkus:latest
    ports:
      - "8080:8080"

  python-metrics:
    image: sesgoe/gmp-min-repro-metrics-python:latest
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
