global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "quarkus-metrics"
    static_configs:
      - targets: ["metrics-app:8080"]
    metrics_path: "/q/metrics"

  - job_name: "python-metrics"
    static_configs:
      - targets: ["python-metrics:8080"]
    metrics_path: "/q/metrics"
